---
title: "CMT_cohort_processing"
output: html_document
date: "2025-10-13"
---
# Loading necessary packages
```{r}
install.packages("pacman")
library(pacman)
pacman::p_load(data.table, stringr, purrr, dplyr)

```


# Loading files
```{r}
general <- fread("UKB_general.csv")
eop <- fread("UKB_EOP.csv")
drugs <- fread("UKB_Rx_drugs.csv")
icd <- fread("UKB_icd.csv")

```


# chronic pain phenotype formatting
```{r}
chronic_pain <- data.frame(
  eid = general$eid,
  age = general$p21022,
  sex = general$p31,
  chronic_pain = rowSums(general[,6:13], na.rm=TRUE) >= 1
)
chronic_pain$chronic_pain[chronic_pain$chronic_pain == TRUE] <- 1
chronic_pain$chronic_pain[chronic_pain$chronic_pain == FALSE] <- 0
```


# neuropathic pain phenotype formatting
```{r}
eop <- as.data.frame(eop)
keep <- c("eid", "p120046","p120047","p120048","p120049","p120050","p120051","p120052")
eop <- eop[, (names(eop)) %in% keep]

neuropathic_pain <- data.frame(
  eid = eop$eid,
  neuropathic_pain = (rowSums(eop[, c(2:8)], na.rm = FALSE)) >= 3
)

neuropathic_pain$neuropathic_pain[neuropathic_pain$neuropathic_pain == TRUE] <- 1
neuropathic_pain$neuropathic_pain[neuropathic_pain$neuropathic_pain == FALSE] <- 0

```


# Prescription drug formatting
```{r}
# generating columns for each of the drug classes
prescriptions <- drugs %>%
  mutate(
    pregabalin = ifelse(str_detect(drug_name, regex("pregabalin|lyrica", ignore_case = TRUE)), 1, 0),
    gabapentin = ifelse(str_detect(drug_name, regex("gabapentin|neurontin|gralise", ignore_case = TRUE)), 1, 0),
    oxycodone = ifelse(str_detect(drug_name, regex("oxycodone|oxycontin", ignore_case = TRUE)), 1, 0),
    duloxetine = ifelse(str_detect(drug_name, regex("duloxetine|cymbalta", ignore_case = TRUE)), 1, 0),
    valproate_sodium = ifelse(str_detect(drug_name, regex("valproate sodium|divalproex|depakote", ignore_case = TRUE)), 1, 0),
    amitriptyline = ifelse(str_detect(drug_name, regex("amitriptyline|elavil", ignore_case = TRUE)), 1, 0),
    carbamazepine = ifelse(str_detect(drug_name, regex("carbamazepine|tegretol|carbatrol", ignore_case = TRUE)), 1, 0),
    venlafaxine = ifelse(str_detect(drug_name, regex("venlafaxine|effexor", ignore_case = TRUE)), 1, 0),
    desipramine = ifelse(str_detect(drug_name, regex("desipramine|norpramin", ignore_case = TRUE)), 1, 0),
    capsaicin_patch = ifelse(str_detect(drug_name, regex("capsaicin patch|qutenza", ignore_case = TRUE)), 1, 0),
    lidocaine_patch = ifelse(str_detect(drug_name, regex("lidocaine patch|lidoderm", ignore_case = TRUE)), 1, 0),
    dextromethorphan = ifelse(str_detect(drug_name, regex("dextromethorphan", ignore_case = TRUE)), 1, 0),
    tramadol = ifelse(str_detect(drug_name, regex("tramadol|ultram", ignore_case = TRUE)), 1, 0),
    imipramine = ifelse(str_detect(drug_name, regex("imipramine|tofranil", ignore_case = TRUE)), 1, 0),
    baclofen = ifelse(str_detect(drug_name, regex("baclofen|gablofen|lioresal", ignore_case = TRUE)), 1, 0),
    tizanidine = ifelse(str_detect(drug_name, regex("tizanidine|zanaflex", ignore_case = TRUE)), 1, 0),
    cyclobenzaprine = ifelse(str_detect(drug_name, regex("cyclobenzaprine|flexeril", ignore_case = TRUE)), 1, 0),
    dantrolene = ifelse(str_detect(drug_name, regex("dantrium|dantrolene|revonto", ignore_case = TRUE)), 1, 0)
  ) %>%
  group_by(eid) %>%
  summarise(across(pregabalin:dantrolene, ~ as.integer(any(. == 1))), .groups = "drop")

```



# comorbidity data formatting
```{r}
# generating columns for each of the comorbidities
comorbidities <- icd %>%
mutate(
    type2_diabetes = ifelse(str_detect(p41270, regex("E119|E1165", ignore_case = TRUE)), 1, 0),
    diabetic_neuropathy = ifelse(str_detect(p41270, regex("E114|E1141|E1142|E1143", ignore_case = TRUE)), 1, 0),
    rheumatoid_arthritis = ifelse(str_detect(p41270, regex("M069|M06", ignore_case = TRUE)), 1, 0),
    alcohol_abuse = ifelse(str_detect(p41270, regex("F1010|F101", ignore_case = TRUE)), 1, 0),
    epilepsy = ifelse(str_detect(p41270, regex("G40909|G409", ignore_case = TRUE)), 1, 0),
    trigeminal_neuropathy = ifelse(str_detect(p41270, regex("G508", ignore_case = TRUE)), 1, 0),
    polyneuropathy = ifelse(str_detect(p41270, regex("G622|G629|G63", ignore_case = TRUE)), 1, 0),
    disc_disorders = ifelse(str_detect(p41270, regex("M50|M51|M5104", ignore_case = TRUE)), 1, 0),
    radiculopathy = ifelse(str_detect(p41270, regex("M54|M541|M5410", ignore_case = TRUE)), 1, 0),
    back_pain = ifelse(str_detect(p41270, regex("M545", ignore_case = TRUE)), 1, 0),
    osteoarthritis = ifelse(str_detect(p41270, regex("M1990|M199|M159|M161|M171", ignore_case = TRUE)), 1, 0),
    sjogrens_syndrome = ifelse(str_detect(p41270, regex("M3500|M350|M35", ignore_case = TRUE)), 1, 0)
  )
comorbidities <- as.data.frame(subset(comorbidities, select = -p41270))

```


# Merging data into a single file
```{r}

df_list <- list(chronic_pain, prescriptions, comorbidities, neuropathic_pain)
pheno_data <- purrr::reduce(df_list, full_join, by = "eid")
write.csv(pheno_data, "pheno_data.csv", quote = FALSE, row.names = FALSE)
```

